apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: chatbot-0610-vllm
  janus-idp.io/tekton: chatbot-0610-vllm
  backstage.io/kubernetes-id: chatbot-0610-vllm
  backstage.io/kubernetes-namespace: rhtap-app-devlopment 
  app.kubernetes.io/part-of: chatbot-0610-vllm
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment.yaml
- route.yaml
- service.yaml
